import { Providers } from "./components/utils/providers"
import "./globals.css"
import { inter } from "./components/utils/fonts"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${inter.className} font-medium`}>
         <Providers>{children}</Providers>
        </body>
    </html>
  )
}
