import { Providers } from "./components/utils/providers"
import "./globals.css"
import { inter } from "./components/utils/fonts"
import Navbar from "./components/sections/Navbar"
import Footer from "./components/sections/Footer"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} font-medium`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
